### ISSUE TITLE
Add MMTF support

### ISSUE THREAD

**Issue by benmwebb** [ihmwg/python-ihm#11]
For smaller output files, it may be useful to encode at least a subset of the IHM dictionary such that it can be written out/read in in MMTF format.

**Comment by benmwebb** [comment]
This appears to be difficult since MMTF encodes slightly different information than mmCIF itself (so MMTF would need to be extended to include our IHM-specific categories). But the library does now support BinaryCIF, which is a more compact binary encoding of the same information that is stored in mmCIF files.

**Comment by aozalevsky** [comment]
I believe this one could be closed as "wontfix" since MMTF is officially [deprecated](https://www.rcsb.org/news/feature/65a1af31c76ca3abcc925d0c).

**Comment by benmwebb** [comment]
Agreed, we support BinaryCIF instead.
