### ISSUE TITLE
Database location names should follow controlled vocabulary

### ISSUE THREAD

**Issue by aozalevsky** [ihmwg/python-ihm#116]
Database names are stored in the controlled [vocabulary](https://mmcif.wwpdb.org/dictionaries/mmcif_ihm.dic/Items/_ihm_dataset_related_db_reference.db_name.html). Thus if a user uses a generic class `ihm.location.DatabaseLocation` and assigns a custom `db_name` (as recommended in the [docs](https://python-ihm.readthedocs.io/en/latest/location.html#ihm.location.Location))
```
Alternatively the resource may be found in an experiment-specific 
database such as PDB or EMDB - for this use [DatabaseLocation] or one of its subclasses.
```

,  the resulting mmcif file won't pass the validation. The generic `ihm.location.DatabaseLocation` should have name `OTHER` and be protected from overwriting.

**Comment by benmwebb** [comment]
Agreed, this is kind of a holdover from the early days of the dictionary when the database table was in flux.
