### ISSUE TITLE
Discrepancies in entities assignment

### ISSUE THREAD

**Issue by aozalevsky** [ihmwg/python-ihm#120]
XL residues have an empty `entity` attribute, but it can be accessed as `asym.entity` (see example below). Is this intended behavior? It can be puzzling if the user is unfamiliar with the `python-ihm`. 

```python

fname = 'PDBDEV_00000016.cif'
try:
    with open(fname, 'r') as f:
        mmcif, = ihm.reader.read(f)
except UnicodeDecodeError:
    with open(fname, 'r', encoding='latin-1') as f:
        mmcif, = ihm.reader.read(f)
        
restraint = mmcif.restraints[0]
xl = restraint.cross_links[0]

print(xl.residue1.entity)
>>> None

print(xl.residue1.asym.entity)
>>> <ihm.Entity(Nup133)>
```

**Comment by benmwebb** [comment]
This is as designed, but I agree it is a little confusing. Residues can represent both
 - "real" residues in a chain, in which `asym` points to the chain and `entity` is None, or
 - residues in an entity (e.g. an experimentally-identified cross link), in which case `asym` is None and `entity` points to the Entity.

I'll change `entity` in real residues to be a synonym for `asym.entity`.
