### ISSUE TITLE
`make-mmcif.py` does not support certain IHMCIF data items

### ISSUE THREAD

**Issue by brindakv** [ihmwg/python-ihm#145]
Information provided in the input file for `_ihm_modeling_protocol.details` and `_ihm_modeling_protocol_details.struct_assembly_description` are not retained in the output.

**Comment by benmwebb** [comment]
python-ihm does not store a separate "description of the assembly used in the protocol that is different from the assembly description" (i.e. `_ihm_struct_assembly.description`) so to avoid user confusion it does not read or write `_ihm_modeling_protocol_details.struct_assembly_description` (why would it be different anyway?). It can certainly write a value for it if you want, but it would simply be a duplicate of `_ihm_struct_assembly.description`, and I generally try to avoid duplication.

I can certainly add `_ihm_modeling_protocol.details`.

**Comment by brindakv** [comment]
@benmwebb `ihm_residues_not_modeled` is not supported either.

**Comment by benmwebb** [comment]
> @benmwebb `ihm_residues_not_modeled` is not supported either.

Indeed, we never used that category in IMP. Do you have depositions which use it? If so, I can add support.

**Comment by brindakv** [comment]
As part of the curation process, we sometimes add it to the user-provided file and re-upload the file and it is lost when python-ihm processes the file.
