### ISSUE TITLE
Duplicated struct_ref.id

### ISSUE THREAD

**Issue by benmwebb** [ihmwg/python-ihm#149]
Current python-ihm appears to be generating `struct_ref` entries with duplicated `id`. Almost certainly this is caused by 29bab0b74, since this adds separate lists of references for each Entity (as two references should not be considered identical if they relate to different Entities). A fix might be to just keep one list but add the Entity to the reference signature.

**Comment by benmwebb** [comment]
@brindakv I think this bug will result in python-ihm 1.4's make_mmcif mangling depositions, by introducing duplicate `ref_id`s. I'll make a 1.5 release that includes a fix for this.

**Comment by brindakv** [comment]
@benmwebb So I should wait for release 1.5 to update python-ihm in the deposition system?

**Comment by benmwebb** [comment]
> @benmwebb So I should wait for release 1.5 to update python-ihm in the deposition system?

@brindakv Yes, I would definitely avoid 1.4. Sticking with 1.3 should be fine for now.
