### ISSUE TITLE
Add group_id to derived_distance_restraints

### ISSUE THREAD

**Issue by mtrellet** [ihmwg/python-ihm#26]
The IHM dictionary allows the usage of group IDs to create sets of distance restraints. This is particularly useful when a set of restraint has a particular group conditionality that does not apply to other restraints. In HADDOCK we deal a lot with ambiguous restraints and group of restraints that might not be all related.

Currently, as far as I understand, the python-ihm library does not allow to define them nor to write them down.

**Comment by benmwebb** [comment]
You're right in that we don't currently handle `group_id`. I'll add some sort of mechanism to group restraints, since various other restraints also allow grouping.
