### ISSUE TITLE
Change _ihm_chemical_descriptor to _ihm_chemical_component_descriptor in dumper.py

### ISSUE THREAD

**Issue by CAHanke** [ihmwg/python-ihm#41]
According to the IHM-dictionary, the "_ihm_chemical_descriptor" category should be called "_ihm_chemical_component_descriptor" in dumper.py

**Comment by benmwebb** [comment]
@brindakv You called this category `ihm_chemical_descriptor` in the `CX-chemical-descriptors` branch but @CAHanke is correct in that it's called `ihm_chemical_component_descriptor` in the `master` branch. I can change the name in python-ihm of course if this is intentional.

**Comment by brindakv** [comment]
@benmwebb Yes, it is intentional. Please update accordingly. I will delete the `CX-chemical-descriptors` branch.
