### ISSUE TITLE
AttributeError on fetching distance from a LowerUpperBoundDistanceRestraint object

### ISSUE THREAD

**Issue by saijananiganesan** [ihmwg/python-ihm#58]
Calling distance on a LowerUpperBoundDistanceRestraint object produces an attribute error: "AttributeError: 'LowerUpperBoundDistanceRestraint' object has no attribute 'distance' ", not sure if I am doing something wrong.  Exact command: i.distance, where *i* is the restraint object (<ihm.restraint.LowerUpperBoundDistanceRestraint object at 0x7f8d58d78310>).

**Comment by benmwebb** [comment]
`DistanceRestraint` doesn't have a `distance` member; instead it has `distance_lower_limit` and `distance_upper_limit` (which may both be the same, or `None` if a given limit is not applicable). I notice these aren't documented though; I'll correct that.
