### ISSUE TITLE
Reading files with incorrect model numbers

### ISSUE THREAD

**Issue by brindakv** [ihmwg/python-ihm#81]
We recently received a deposition where the uploaded mmCIF file had ten models in the `atom_site` table. However, the `_atom_site.pdbx_PDB_model_num` column had the same model number for all ten models i.e., there were multiple sets of coordinates for the same atom in the same model. `python-ihm` did not throw out an error while reading this mmCIF file.

**Comment by brindakv** [comment]
Right. But the dumper also writes out coordinates for multiple models with the same model number.

**Comment by benmwebb** [comment]
Sure, we could check in the dumper instead, I guess that makes sense. We already check for other wonkiness (e.g. trying to emit atoms for a seq_id that isn't in the representation) so that would be a natural place to do it.
