### ISSUE TITLE
Auto-populate `_ihm_modeling_protocol.ensemble_flag`

### ISSUE THREAD

**Issue by brindakv** [ihmwg/python-ihm#97]
Default value can be set to `NO` unless
- Multiple model groups are present
- `ihm_multi_state_modeling` or `ihm_ordered_ensemble` or `ihm_ensemble_info` or `ihm_ensemble_sub_sample` or `ihm_localization_density_files` or `ihm_gaussian_obj_ensemble` are provided

@benmwebb please add any other valid scenarios.

**Comment by benmwebb** [comment]
This was already done in #83.
